name: Pull Request CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_lint:
    name: 🚧 Build, Lint and Test Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: 📦 Install Dependencies
        run: yarn install --frozen-lockfile --prefer-offline

      - name: 👷 Build app to check for build time errors
        run: yarn build

      - name: 💄 Lint code
        run: yarn lint

      - name: 🧪 Run tests
        run: yarn test
