name: Build and Deploy Storybook

on:
  push:
    branches:
      - main

permissions:
  contents: write

defaults:
  run:
    working-directory: 'packages/apollo-components'

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build ⬇️
        run: |
          yarn install --frozen-lockfile
          yarn build-storybook
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        #if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/apollo-components/storybook-static # The folder the action should deploy.
